FROM tomcat:9.0

LABEL maintainer="rakesh"

EXPOSE 8080

# Remove default Tomcat apps (optional but clean)
RUN rm -rf /usr/local/tomcat/webapps/*

# Copy any WAR file generated by Maven
COPY target/*.war /usr/local/tomcat/webapps/ROOT.war
