apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maven-web-app
  template:
    metadata:
      labels:
        app: maven-web-app
    spec:
      containers:
      - name: maven-web-app
        image: rakesh/mavenwebapp:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: maven-web-app-service
spec:
  type: NodePort
  selector:
    app: maven-web-app
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30007
